salesforce:
  username: ""
  password: ""
  token: ""
  client_id: ""
  client_secret: ""
  loginUrl: "login.salesforce.com"
  requestUrl: "mule.my.salesforce.com"
  requestProtocol: "HTTPS"
 
http:
  listener:
    protocol: "HTTP"
    host: "0.0.0.0"
    port: "8081"
    timeout: "30000"
  